# documentation: https://fshschool.org/docs/sushi/configuration/
# 
id: hl7.fhir.us.pdmp
canonical: http://hl7.org/fhir/us/pdmp
name: PDMP
title: US Prescription Drug Monitoring Program (PDMP)
description: US Prescription Drug Monitoring Program (PDMP) FHIR IG
status: draft # draft | active | retired | unknown
version: 1.0.0-ballot
fhirVersion: 4.0.1 
copyrightYear: 2023+
releaseLabel: STU1-ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
publisher:
  name: HL7 International / Pharmacy
  url: http://www.hl7.org/Special/committees/medication

dependencies:
  hl7.fhir.us.core: 6.1.0

pages:
  index.md:
    title: PDMP IG Home Page
  use-case.md:
    title: Use Cases
  submission-options.md:
    title: Operation Submission Options
  cds-smart.md:
    title: CDS Hooks and SMART App Options
  conformance.md:
    title: Conformance Expectations
  security.md:
    title: Security
  mappings.md:
    title: Mappings to Related Standards
  us-core-profiles.md:
    title: Applicable US Core Profiles
  capability-statements.md:
    title: Capability Statements
  downloads.xml:
    title: Downloads
  changes.md:
    title: Change Log

# menu:
#   Home: index.html
#   Artifacts: artifacts.html
#

contact:
  - name: Frank McKinney
    telecom:
      - system: email
        value: frank.mckinney@pocp.com
      - system: email
        value: fm@frankmckinney.com
  - name: Scott Robertson
    telecom:
      - system: email
        value: scott.robertson@pocp.com
      - system: email
        value: scott@BearHealthTech.consulting
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: phx
auto-oid-root: 2.16.840.1.113883.4.642.40.35
#
#
# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
# See the individual option definitions below for more detail.
#
# instanceOptions:
#   Determines for which types of Instances SUSHI will automatically set meta.profile
#   if InstanceOf references a profile:
#
#   setMetaProfile: always # always | never | inline-only | standalone-only
#
#
#   Determines for which types of Instances SUSHI will automatically set id
#   if InstanceOf references a profile:
#
#   setId: always # always | standalone-only
