# documentation: https://fshschool.org/docs/sushi/configuration/
# 
id: hl7.fhir.us.pdmp
canonical: http://hl7.org/fhir/us/pdmp
name: PDMP
title: US Prescription Drug Monitoring Program (PDMP)
description: US Prescription Drug Monitoring Program (PDMP) FHIR IG
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use | STU1
license: CC0-1.0 
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
publisher:
  name: HL7 International / Pharmacy
  url: http://www.hl7.org/Special/committees/medication

dependencies:
  hl7.fhir.us.core: 6.1.0

#
# pages:
#   index.md:
#     title: Example Home
#   implementation.xml:
#   examples.xml:
#     title: Examples Overview
#     simpleExamples.xml:
#     complexExamples.xml:
#
# menu:
#   Home: index.html
#   Artifacts: artifacts.html
#

contact:
  - name: Frank McKinney
    telecom:
      - system: email
        value: frank.mckinney@pocp.com
      - system: email
        value: fm@frankmckinney.com

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: phx
#
#
# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
# See the individual option definitions below for more detail.
#
# instanceOptions:
#   Determines for which types of Instances SUSHI will automatically set meta.profile
#   if InstanceOf references a profile:
#
#   setMetaProfile: always # always | never | inline-only | standalone-only
#
#
#   Determines for which types of Instances SUSHI will automatically set id
#   if InstanceOf references a profile:
#
#   setId: always # always | standalone-only
